### ISSUE TITLE
tosback.org -> edit.tosdr.org bridge

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/tosback-crawler#6]
Taking https://github.com/tosdr/tosback-versions/blob/master/Twitch/Privacy%20Policy.md as an example.

```mysql
phoenix_development=# select id,name,url from documents where service_id=200 and name='Privacy Policy';
 id  |      name      |                      url                      
-----+----------------+-----------------------------------------------
 317 | Privacy Policy | https://www.twitch.tv/p/legal/privacy-policy/
(1 row)

**Comment by michielbdejong** [comment]
https://github.com/tosdr/edit.tosdr.org/blob/master/db/import_from_tosback2.rb

**Comment by michielbdejong** [comment]
The node process on tosback.org could write directly to the live postgres db on Heroku.
And then it should also do the points-review from https://github.com/tosdr/edit.tosdr.org/blob/master/db/import_from_tosback2.rb#L48 in Node.

**Comment by michielbdejong** [comment]
maybe i can just do trigger this from the Notifier

**Comment by michielbdejong** [comment]
```sh
saving to edit.tosdr.org Advanceautoparts Terms of Service d5e9c6c

**Comment by michielbdejong** [comment]
```sh
commit d616cd5a40726d6d8a2b52ed9f5931adcee62ba3
Author: Tosback Crawler <tosback@unhosted.org>
Date:   Fri Nov 20 04:33:41 2020 -0500

    Start tracking Advanceautoparts Terms of Service
    
    This version was recorded after filtering snapshot https://github.com/tosdr/tosback-snapshots/commit/d5e9c6c

**Comment by michielbdejong** [comment]
https://github.com/tosdr/tosback-versions/commit/d616cd5a40726d6d8a2b52ed9f5931adcee62ba3

**Comment by michielbdejong** [comment]
```
2020-11-20 04:33:41 error AeroBase Group — Terms of Service                       Error: Client has already been connected. You cannot reuse a client.
    at Client._connect (/home/tosback3/tosback-crawler/node_modules/pg/lib/client.js:94:19)
    at /home/tosback3/tosback-crawler/node_modules/pg/lib/client.js:166:12
    at new Promise (<anonymous>)
    at Client.connect (/home/tosback3/tosback-crawler/node_modules/pg/lib/client.js:165:12)
    at Notifier.saveToEditTosdrOrg (file:///home/tosback3/tosback-crawler/src/notifier/index.js:52:29)
    at CGUs.recordVersion (file:///home/tosback3/tosback-crawler/src/app/index.js:197:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
/home/tosback3/tosback-crawler/node_modules/async/dist/async.js:181
            setImmediate$1(e => { throw e }, err);
                                  ^

Error: Client has already been connected. You cannot reuse a client.
    at Client._connect (/home/tosback3/tosback-crawler/node_modules/pg/lib/client.js:94:19)
    at /home/tosback3/tosback-crawler/node_modules/pg/lib/client.js:166:12
    at new Promise (<anonymous>)
    at Client.connect (/home/tosback3/tosback-crawler/node_modules/pg/lib/client.js:165:12)
    at Notifier.saveToEditTosdrOrg (file:///home/tosback3/tosback-crawler/src/notifier/index.js:52:29)

**Comment by michielbdejong** [comment]
I've got something working and tried it out on the Twitter PP.  Only 1 out of 12 points survived the switch to markdown. Need to think about how I can automate this.

**Comment by michielbdejong** [comment]
algorithm: Run through the list of words in the existing quote
if you find one that matches exactly once, cling to that.
go back to align earlier words, but don't skip more than 2 or 3 
go forward to align all further words, but don't skip more than 2 or 3 

example:
quote: a a b c d d e
doc: bla bla bla a b x c d e e bla bla bla
---
* a -> occurs twice, skip it
* b -> pin to 'b'
* go back, pin 'a b' to 'a b'
* go forward, pin 'a b c d [d] e' to 'a b [x] c d e'

**Comment by michielbdejong** [comment]
Made a start with a quote-matching algorithm. Will continue on Monday.

**Comment by michielbdejong** [comment]
It needs a sourceMap from words back to characters so we can calculate the true new quoteStart/quoteEnd positions.
